"""
https://leetcode.com/problems/find-the-difference/#/description


Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s
and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        scount = {}
        tcount = {}
        for x in set(s):
            scount[x] = s.count(x)
        for x in set(t):
            tcount[x] = t.count(x)
        return list(set(tcount.items()) - set(scount.items()))[0][0]
